version: "3"
services:
  nginx:
    image: dji/nginx:latest
    networks:
      - cloud_service_bridge
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime
  cloud_api_sample:
    image: dji/cloud_api_sample:latest
    depends_on:
      - mysql
      - emqx
      - redis
    ports:
      - "6789:6789"
    volumes:
      - /etc/localtime:/etc/localtime
    hostname: cloud_api_sample
    restart: "always"
    networks:
      - cloud_service_bridge
  emqx:
    image: emqx:4.4
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
    hostname: emqx-broker
    networks:
      - cloud_service_bridge
  mysql:
    image: dji/mysql:latest
    networks:
      - cloud_service_bridge
    ports:
      - "3308:3306"
    volumes:
      # - /etc/group:/etc/group:ro
      # - /etc/passwd:/etc/passwd:ro
      - /etc/localtime:/etc/localtime
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    hostname: cloud_api_sample_mysql
  redis:
    image: redis:6.2
    restart: "always"
    hostname: cloud_api_sample_redis
    ports:
      - "6379:6379"
    networks:
      - cloud_service_bridge
    command: redis-server

networks:
  cloud_service_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.6.0/24
